/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.automobiles.tables.daos;


import com.example.demo.db.automobiles.tables.Auto;
import com.example.demo.db.automobiles.tables.records.AutoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutoDao extends DAOImpl<AutoRecord, com.example.demo.db.automobiles.tables.pojos.Auto, Integer> {

    /**
     * Create a new AutoDao without any configuration
     */
    public AutoDao() {
        super(Auto.AUTO, com.example.demo.db.automobiles.tables.pojos.Auto.class);
    }

    /**
     * Create a new AutoDao with an attached configuration
     */
    public AutoDao(Configuration configuration) {
        super(Auto.AUTO, com.example.demo.db.automobiles.tables.pojos.Auto.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.demo.db.automobiles.tables.pojos.Auto object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.demo.db.automobiles.tables.pojos.Auto> fetchById(Integer... values) {
        return fetch(Auto.AUTO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.demo.db.automobiles.tables.pojos.Auto fetchOneById(Integer value) {
        return fetchOne(Auto.AUTO.ID, value);
    }

    /**
     * Fetch records that have <code>brand IN (values)</code>
     */
    public List<com.example.demo.db.automobiles.tables.pojos.Auto> fetchByBrand(String... values) {
        return fetch(Auto.AUTO.BRAND, values);
    }

    /**
     * Fetch records that have <code>model IN (values)</code>
     */
    public List<com.example.demo.db.automobiles.tables.pojos.Auto> fetchByModel(String... values) {
        return fetch(Auto.AUTO.MODEL, values);
    }

    /**
     * Fetch a unique record that has <code>model = value</code>
     */
    public com.example.demo.db.automobiles.tables.pojos.Auto fetchOneByModel(String value) {
        return fetchOne(Auto.AUTO.MODEL, value);
    }
}
