/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.automobiles.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auto implements Serializable {

    private static final long serialVersionUID = 498052964;

    private Integer id;
    private String  brand;
    private String  model;

    public Auto() {}

    public Auto(Auto value) {
        this.id = value.id;
        this.brand = value.brand;
        this.model = value.model;
    }

    public Auto(
        Integer id,
        String  brand,
        String  model
    ) {
        this.id = id;
        this.brand = brand;
        this.model = model;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Auto (");

        sb.append(id);
        sb.append(", ").append(brand);
        sb.append(", ").append(model);

        sb.append(")");
        return sb.toString();
    }
}
