/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.automobiles.tables;


import com.example.demo.db.automobiles.Automobiles;
import com.example.demo.db.automobiles.Indexes;
import com.example.demo.db.automobiles.Keys;
import com.example.demo.db.automobiles.tables.records.AutoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Auto extends TableImpl<AutoRecord> {

    private static final long serialVersionUID = -1232913725;

    /**
     * The reference instance of <code>automobiles.auto</code>
     */
    public static final Auto AUTO = new Auto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AutoRecord> getRecordType() {
        return AutoRecord.class;
    }

    /**
     * The column <code>automobiles.auto.id</code>.
     */
    public final TableField<AutoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>automobiles.auto.brand</code>.
     */
    public final TableField<AutoRecord, String> BRAND = createField("brand", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>automobiles.auto.model</code>.
     */
    public final TableField<AutoRecord, String> MODEL = createField("model", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>automobiles.auto</code> table reference
     */
    public Auto() {
        this(DSL.name("auto"), null);
    }

    /**
     * Create an aliased <code>automobiles.auto</code> table reference
     */
    public Auto(String alias) {
        this(DSL.name(alias), AUTO);
    }

    /**
     * Create an aliased <code>automobiles.auto</code> table reference
     */
    public Auto(Name alias) {
        this(alias, AUTO);
    }

    private Auto(Name alias, Table<AutoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Auto(Name alias, Table<AutoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Auto(Table<O> child, ForeignKey<O, AutoRecord> key) {
        super(child, key, AUTO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Automobiles.AUTOMOBILES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTO_ID, Indexes.AUTO_MODEL, Indexes.AUTO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AutoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AutoRecord> getPrimaryKey() {
        return Keys.KEY_AUTO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AutoRecord>> getKeys() {
        return Arrays.<UniqueKey<AutoRecord>>asList(Keys.KEY_AUTO_PRIMARY, Keys.KEY_AUTO_ID, Keys.KEY_AUTO_MODEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Auto as(String alias) {
        return new Auto(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Auto as(Name alias) {
        return new Auto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Auto rename(String name) {
        return new Auto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Auto rename(Name name) {
        return new Auto(name, null);
    }
}
