/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db;


import com.example.demo.db.automobiles.Automobiles;
import com.example.demo.db.information_schema.InformationSchema;
import com.example.demo.db.mysql.Mysql;
import com.example.demo.db.performance_schema.PerformanceSchema;
import com.example.demo.db.sys.Sys;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 2007637602;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>mysql</code>.
     */
    public final Mysql MYSQL = com.example.demo.db.mysql.Mysql.MYSQL;

    /**
     * The schema <code>information_schema</code>.
     */
    public final InformationSchema INFORMATION_SCHEMA = com.example.demo.db.information_schema.InformationSchema.INFORMATION_SCHEMA;

    /**
     * The schema <code>performance_schema</code>.
     */
    public final PerformanceSchema PERFORMANCE_SCHEMA = com.example.demo.db.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA;

    /**
     * The schema <code>sys</code>.
     */
    public final Sys SYS = com.example.demo.db.sys.Sys.SYS;

    /**
     * The schema <code>automobiles</code>.
     */
    public final Automobiles AUTOMOBILES = com.example.demo.db.automobiles.Automobiles.AUTOMOBILES;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            Mysql.MYSQL,
            InformationSchema.INFORMATION_SCHEMA,
            PerformanceSchema.PERFORMANCE_SCHEMA,
            Sys.SYS,
            Automobiles.AUTOMOBILES);
    }
}
