/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.automobiles;


import com.example.demo.db.DefaultCatalog;
import com.example.demo.db.automobiles.tables.Auto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Automobiles extends SchemaImpl {

    private static final long serialVersionUID = 61245786;

    /**
     * The reference instance of <code>automobiles</code>
     */
    public static final Automobiles AUTOMOBILES = new Automobiles();

    /**
     * The table <code>automobiles.auto</code>.
     */
    public final Auto AUTO = com.example.demo.db.automobiles.tables.Auto.AUTO;

    /**
     * No further instances allowed
     */
    private Automobiles() {
        super("automobiles", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Auto.AUTO);
    }
}
