/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db.automobiles;


import com.example.demo.db.automobiles.tables.Auto;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in automobiles
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>automobiles.auto</code>.
     */
    public static final Auto AUTO = com.example.demo.db.automobiles.tables.Auto.AUTO;
}
